version: '3.8'

services:
  api:
    image: cs-managers:development
    environment:
      - .env.compose-api
    build:
      context: .
    ports:
      - 3000:80
    command: bin/start-api.sh
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cs_managers_development

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
